### PR TITLE
fixed stuff main.py

### PR DESCRIPTION
**Pull request by ShinKamiZ**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

**Describe the changes proposed in the pull request** A quick description of the changes made to the repository

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior** (if this is a feature change)?

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information:**

### CODE REVIEW

**Comment by logicguy1** [comment]
Bro you didn't fix anything lol

**Comment by ShinKamiZ** [comment]
breh xd srsly? i thought my friend fixed it... sorry then 😅

**Comment by logicguy1** [comment]
I mean you didnt change anything in the code so i dont pressen do

**Comment by ShinKamiZ** [comment]
yea i think my frend didnt do much...do you want me to take the thing down?

**Comment by logicguy1** [comment]
No ill just close it

**Comment by ShinKamiZ** [comment]
Ok

**Pull request closed without merging**
