### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by saw21e**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

**Describe the changes proposed in the pull request** A quick description of the changes made to the repository

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior** (if this is a feature change)?

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information:**

### CODE REVIEW

**Comment by saw21e** [comment]
@everyone

**Comment by logicguy1** [comment]
Your PR has no content

**Comment by logicguy1** [comment]
Useless PR

**Review by logicguy1 — COMMENTED** [review]
Seems good but some slight adjustments might be needed to make this fit proper

**Pull request closed without merging**
